export const podcasts = [
  {
    id: 1,
    title: "The Future of AI Leadership",
    episode: "Episode 01",
    coverImage: "/team1.jpg",
    audioUrl: "/podcast.mp3",
    duration: "32:14",
  },
  {
    id: 2,
    title: "Building Global Brands",
    episode: "Episode 02",
    coverImage: "/team2.jpg",
    audioUrl: "/podcast.mp3",
    duration: "41:02",
  },
  {
    id: 3,
    title: "Women in Innovation",
    episode: "Episode 03",
    coverImage: "/team3.jpg",
    audioUrl: "/podcast.mp3",
    duration: "27:45",
  },
  {
    id: 4,
    title: "Scaling Startups Smartly",
    episode: "Episode 04",
    coverImage: "/team3.jpg",
    audioUrl: "/podcast.mp3",
    duration: "36:19",
  },
  {
    id: 5,
    title: "Digital Transformation",
    episode: "Episode 05",
    coverImage: "/team5.jpg",
    audioUrl: "/podcast.mp3",
    duration: "29:54",
  },
  {
    id: 6,
    title: "The Power of Storytelling",
    episode: "Episode 06",
    coverImage: "/team2.jpg",
    audioUrl: "/podcast.mp3",
    duration: "38:22",
  },
]